# Generated by Django 5.1.2 on 2024-11-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('lorong_id', models.IntegerField()),
                ('room_number', models.CharField(max_length=4)),
                ('major_id', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
