# Generated by Django 5.1.2 on 2024-11-01 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lorong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lorong_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=255)),
                ('lorong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lorong')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
