# Generated by Django 5.1.2 on 2024-11-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lorong_paymentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room_number',
        ),
    ]
